[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
image = "0.25.5"
itertools = "0.13.0"
nalgebra = "0.33.2"
regex = "1.11.1"
seq-macro = "0.3.5"
